#!/bin/sh

for cppstd in c++98 gnu++98 c++03 gnu++03 c++11 gnu++11 c++14 gnu++14 c++17 gnu++17 c++20 gnu++20 c++2a gnu++2a
do
   printf "cppstd = %-7s : %s\n" $cppstd  $( echo '__cplusplus' | gcc -E -x c++ -std=$cppstd - | grep -v '^#' ) 
done
